#include <stdio.h>
#include <stdlib.h>
#include <string.h>

char* content = NULL;

void Append(char** output, const char* str)
{
    char* tmp = *output;
    int oldlen = tmp == NULL ? 0 : strlen(tmp);
    int newlen = oldlen + strlen(str) + 1;
    tmp = realloc(tmp, newlen);
    tmp[newlen - 1] = 0;
    sprintf(tmp + oldlen, "%s", str);
    *output = tmp;
}

int main()
{
    Append(&content, "<html><body><h1>Hello, World!</h1></body></html>\r\n");
    Append(&content, "<p>This is a simple HTML page generated by C.</p>\r\n");
    printf("%s\n", content);
    free(content);
    content = NULL;
}